services:
  threejs-app:
    image: physics
    container_name: physics
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    volumes:
      - .:/app
      - /app/node_modules

    networks:
      - physics-net

    restart: unless-stopped


networks:
  physics-net:
    driver: bridge